// <auto-generated />
namespace EIRLSSAssignment1.Migrations.MigrationContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddReferenceToBooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddReferenceToBooking));
        
        string IMigrationMetadata.Id
        {
            get { return "202101011435500_AddReferenceToBooking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
